name: Build

on:
  push:
    branches: [main]
    paths: [.github/workflows/*, src/**, include/**, CMakeLists.txt]
  pull_request:
    branches: [main]
    paths: [.github/workflows/*, src/**, include/**, CMakeLists.txt]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        toolchain:
          - { id: dkp, name: devkitPro, container: devkitpro/devkitarm:latest, preset: dkp-release }
          - { id: blocks, name: BlocksDS, container: skylyrac/blocksds:slim-latest, preset: blocksds-release }

    name: ${{ matrix.toolchain.name }}
    runs-on: ubuntu-latest
    container: ${{ matrix.toolchain.container }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install CMake
        if: ${{ matrix.toolchain.id }} == 'blocks'
        run: apt-get install -y cmake && which cmake

      - name: Configure CMake
        run: cmake --preset ${{ matrix.toolchain.preset }}

      - name: Build project
        run: cmake --build build -j

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: nds-shell
          path: ./build/nds-shell.*
          if-no-files-found: error
